### ISSUE TITLE
PHP Socket module not enabled

### ISSUE THREAD

**Issue by kylerw** [d8ahazard/docker-phlex#1]
Error:

[22-Mar-2017 12:20:07 America/Chicago] PHP Fatal error:  Uncaught Error: Call to undefined function socket_create() in /config/www/Phlex/cast/mdns.php:16
Stack trace:
#0 /config/www/Phlex/cast/Chromecast.php(54): mDNS->__construct()
#1 /config/www/Phlex/api.php(1463): Chromecast::scan()
#2 /config/www/Phlex/api.php(1437): fetchCastDevices()
#3 /config/www/Phlex/api.php(400): fetchDevices('clients')
#4 /config/www/Phlex/api.php(213): setSessionVariables()
#5 {main}
  thrown in /config/www/Phlex/cast/mdns.php on line 16

**Comment by kylerw** [comment]
Looks like installing sockets and fpm helped. Still no cast devices.

apk add php5-sockets
apk add php5-fpm

**Comment by d8ahazard** [comment]
Same here - I've updated the image so that sockets and all that jazz work, but it seems like the MDNS responses can't get into the container.  I'm going to take this up with @ChrisRidings over email, see if we can get it working now that I've fixed the container.
