### ISSUE TITLE
Nginx Server API Token Reset

### ISSUE THREAD

**Issue by bezmi** [d8ahazard/docker-phlex#15]
Hi,

I'm currently working on integrating this docker container into the Hass.io platform as an add-on, and storing the Phlex folder in persistent storage. After logging in and setting up Phlex, when the docker container is reset, I'm greeted by a fresh log in screen and when I do that, the Phlex API token is changed (causing me to loose voice control) and the Sonarr and Radarr API tokens are not present any longer. Other settings such as public address, etc are saved. Is this desired behaviour or a bug? This also happens in non dockerized form when restarting nginx in Arch Linux.

I should note that running Phlex in Xampp under windows, restarting the server does not result in a fresh log in screen as it does under nginx.

**Comment by Jolanrensen** [comment]
perhaps you have to use the /data directory to store these settings as described in the python example https://home-assistant.io/developers/hassio/addon_tutorial/. I'm not sure, but I think this has something to do with docker starting anew and setting everything up from the beginning again at a restart

**Comment by bezmi** [comment]
I'm already storing the www directory in data for persistent storage. Trying this with nginx on my arch linux install (not in docker) results in the same behaviour when restarting the server, where it asks me to log in again and settings are stored, but all API tokens are reset.

**Comment by Jolanrensen** [comment]
aah okay... hmm... unfortunately xampp isn't available for hassio is it? I tried to make it work using the built in web server of php, but then I missed some extensions, couldn't get it to work, but perhaps you could

**Comment by bezmi** [comment]
Well xampp could be installed in a docker container but it's not available for armhf architecture, which is what I need to run it on a raspberry pi. I am currently implementing the docker container with apache so we'll see how it goes

**Comment by bezmi** [comment]
I've resolved the issue. I did not have a username set up for plex, so logging in with just email resulted in some errors in the Phlex api. The code currently available in my [repository](https://github.com/bezmi/addon-phlex) is working, but ssl functionality has not yet implemented.
