### ISSUE TITLE
Cast Plugin Not Found!

### ISSUE THREAD

**Issue by jfjallid** [d8ahazard/docker-phlex#24]
I'm running Plex in a docker container in default network mode and expose port 32400.
I'm running Phlex in network mode host and in privileged mode.
I've extracted the Cast.bundle to my Plex server plugin directory and I can see the plugin in my Plex gui.

When I access the Phlex web gui I get the message: "Cast Plugin Not Found!" and no Chromecast is found in the cast device list.

**Comment by d8ahazard** [comment]
You'll need to check in the *Plex* GUI and see if the plugin can even find
any devices. If not, then you'll want to try binding port 5353 to 5353 of
your synology, *OR*, connecting Plex's network in host mode.

I'm not sure if it's possible to bind 5353 directly, but it needs to be
able to send/receive UDP data in order to discover devices. :/

**Comment by jfjallid** [comment]
Okey, I noticed that it did not list any cast device under the plugin. So I'm running my plex instance behind a reverse proxy and therefore can't be in network mode host.

I tried launching a second instance of plex in network mode host without any remote access or libraries and installed the plugin. The plugin on that server can see my web browser as a cast device but it does not see my chromecasts on the same network.

Edit:
Forgot to allow port 5353 through the firewall. Phlex could detect my chromecasts when I had a second plex instance with the plugin running on the network in network mode host. However, all playback failed so I'm wondering if the the second plex instance might have interfered somehow.

I also tried with just one plex instance and binding port 5353 to 5353 for udp on the container, but in that setup the plugin only detected my browser but not the chromecasts.

**Comment by jfjallid** [comment]
I decided to find a workaround for the problem preventing me from running plex in network mode host instead which turned out to be the simpler approach. Now it detects the chromecasts correctly and everything seems to be in order. 

However, it would be nice if the cast.bundle was standalone instead of a plex plugin if that would allow for an environment where plex is located on one network, and phlex and the chromecasts on another.

**Comment by d8ahazard** [comment]
It's on my to-do list...
